### ISSUE TITLE
Cannot change the "Deck Settings" (l) shortcut

### ISSUE THREAD

**Issue by Farinata** [Yutsuten/anki-lifedrain#122]
**Anki version & Operating System:** 
Last, windows 10
**Describe the bug:** 
I cannot change the global setting and the deck setting shortcuts (l) and (Ctrl+l). Very very annoying. I reported this issue on ankiweb 1 year ago and stopped using the Lifedrain because of this bug, now when I returned it is still there.
Actually can change them, but will automatically return to the (l) default after one day or two. 
The problem is that (l) is the good answer shortcut.
Either there is a conflict with another addon (I have many and no time to test), or a bug in the lifedrain (the most probable).
I don't care at all about these 2 shortcuts. Can I permanently remove these 2 shortcuts?

P.S I tried also leaving them empty, but same problem will refill will (l) after a day.

**Comment by Yutsuten** [comment]
I have the latest Anki (2.1.49) too, and I'll try changing the default shortcut for a few days to see if I can reproduce this bug.

But if I were to guess what is happening, or there is an addon that is deleting the settings from the database (I'm very sure my addon don't do it) and therefore the shortcuts are being reset to the defaults, or on newer versions of Anki is doing some settings deletion (very unlikely).

> Actually can change them, but will automatically return to the (l) default after one day or two.

This is a **very** strange behaviour. My addon don't ever reset any settings from the user.

For now you can change my code directly to remove the shortcuts. On the file **main.py**, comment out (add the `#` character before [line 23](https://github.com/Yutsuten/anki-lifedrain/blob/v2.4.2/src/main.py#L23) (or delete it if you prefer).

```diff
+    setup_shortcuts(lifedrain)
-    # setup_shortcuts(lifedrain)
```

**Be careful** to not change the indentation. Python is very strict about the spaces on the left.

---

Anyway, I'll try to reproduce it. I'll tell the results after a few days.

**Comment by Yutsuten** [comment]
I was able to reproduce it once, but still don't know the steps and the bug isn't happening anymore. I think the bug happened after I synced with AnkiDroid, but it is not happening anymore. I also tried upgrading my Anki to the very latest version (2.1.50, still not released) in that time, so it may be the cause?

Anyway, I'll keep investigating.

**Comment by Yutsuten** [comment]
I couldn't reproduce it anymore, but there is a fix that *may* work for this issue.
I haven't released this change yet, but you can try the change I did in #124 .

**Comment by Yutsuten** [comment]
Not sure if I can call this a fix, but I'm considering changing the shortcuts defaults to disabled.

**Comment by Yutsuten** [comment]
I found a way to reproduce this bug. It happens every time I study in AnkiDroid. Seems that AnkiDroid keeps old Lifedrain configuration in its database, and does not update it when syncing **from** the cloud. But it does overwrite the configuration when syncing **to** the cloud.

The bug is not limited to shortcuts configuration. For me the bug was resetting to an old bar style (colors and position). So I guess it affects all configurations.

This is indeed annoying.

I'll change the DB backend. I was using the same DB as Anki itself, but seems that saving to a JSON file should be the solution. We will lose the feature where you could sync Lifedrain configuration between multiple PCs, but I guess there is no other solution.
