### ISSUE TITLE
Health jumps down when rescheduled using ReMemorize

### ISSUE THREAD

**Issue by StookDog** [Yutsuten/anki-lifedrain#47]
Hi,

I've been experiencing a bug where the health jumps down ~10 points after rescheduling a card using the ReMemorize addon. I have lifedrain set to No damage, and to pause when I'm on the answer screen so I'm not sure where the damage is coming from. Thanks!

**Comment by Yutsuten** [comment]
Hello @StookDog , thank you for reporting this bug!

---

Maybe I know what is the problem. Could you try something for me?
On `lifedrain.py` could you comment out lines 771 and 772?

https://github.com/Yutsuten/anki-lifedrain/blob/a0b7dadf0157ea6743816237f5a7c0c31aa91369/lifedrain/lifedrain.py#L771-L772

Just add a `#` before those lines:

```python
#addHook('reset', undo)
#addHook('revertedCard', lambda cid: undo())
```

Restart Anki and check if the issue persists.

After trying this, could you tell me the results?

**Comment by StookDog** [comment]
I commented out those lines and it looks like it worked! Thanks for finding that. Will that break any other features or is it ok to leave as is?

**Comment by Yutsuten** [comment]
You disabled a feature that removes the life whenever the user undoes (e.g. `ctrl+z`) during a review. I added this feature because sometimes I undo to give a different answer to a card I answered wrongly.

But if you don't care about it, or don't undo cards, you can leave those lines commented.

I'll look for why ReMemorize is triggering the `undo` code, then I'll try to fix it on my side.

**Comment by Yutsuten** [comment]
I was testing here and seems that removing only `addHook('reset', undo)` is enough to fix the problem and keep the Life Drain's undo feature.

That hook was probably needed on Anki 2.0, but I think its safe to remove already.

The next release of Life Drain will contain this fix. Thank you for reporting it!
