### ISSUE TITLE
Allow configuring special actions behavior

### ISSUE THREAD

**Issue by Yutsuten** [Yutsuten/anki-lifedrain#51]
~Suspending/burying should be considered a neutral action, so life should not be affected.~

Allow users to configure the behavior of special actions like suspending, burying, undoing.
Possible options: drain life, do nothing, recover.

**Comment by jamiekoi** [comment]
Also undo Cmd + Z?

Why I think it's neutral: most of the time I wanna whiz through my reviews fast, however, sometimes I wanna do a double take and look at the extra section of the previous reviewed card because I had gone too fast, so I Cmd + Z to go back to it, read it quick, then go back to my reviews queues

Right now Cmd + Z drains life. Not a big issue, just a suggestion if it is possible to make it neutral.

**Comment by Yutsuten** [comment]
@jamiekoi sorry for the late answer.
Probably there are many reasons/use cases for people to disable the damage on undo. I think things like this is nice to have in the user options.

I'll create a new issue for this, as this one is not for the undo feature.

Thank you for the feedback.

**Comment by Yutsuten** [comment]
I've made the issue more generic, looks better now in my opinion.
I guess that with this #58 became a duplicated of this one.
